[package]
name = "hyfetch"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
default-run = "hyfetch"

[dependencies]
# ansi_colours = { workspace = true, features = ["rgb"] }
anyhow = { workspace = true, features = ["std"] }
bpaf = { workspace = true, features = [] }
chrono = { workspace = true, features = ["clock", "std"] }
# derive_more = { workspace = true, features = ["std"] }
indexmap = { workspace = true, features = ["std"] }
neofetch = "0.1.4"
pyo3 = { version = "0.22.0", features = ["auto-initialize"] }
rgb = { workspace = true, features = [] }
shell-words = { workspace = true, features = ["std"] }
strum = { workspace = true, features = ["derive", "std"] }
tracing = { workspace = true, features = ["attributes", "std"] }
tracing-subscriber = { workspace = true, features = ["ansi", "fmt", "smallvec", "std", "tracing-log"] }
termion = "*"
regex.workspace = true
which = "6.0.1"
shlex = "1.3.0"
tempfile = "3.10.1"

[build-dependencies]
indexmap = { workspace = true, features = ["std"] }
regex = { workspace = true, features = ["perf", "std", "unicode"] }
unicode-normalization = { workspace = true, features = ["std"] }

[features]
default = ["autocomplete", "color"]
autocomplete = ["bpaf/autocomplete"]
color = ["bpaf/dull-color"]
